telegram_token: <value> # Telegram token id
chatbase_token: <value> # Chatbase token for store statistic
pause_mailing: 10 # Delay between messages in mailing

# Messages for events
messages:
  start: "Hello! I can add correct line breaks to your Instagram post. "
  help: "Just send me a text."
  loading: "Your data is loading ..."
  metadata: "Length: {}/2200 \n Number of hashtags: {}/30"